# -*- coding: utf-8 -*-
"""LoanData_Statistics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pEfsiPfWk48qT6IH9lU5qeVipSKktveG

#Statistics Final Project - Data Analytics
#####Glorious Satria Dhamang Aji - 1302213015
#####Farhan Mulya Argyanto - 1302213073

###Import Library
"""

install.packages("moments")
library(moments)
install.packages("psych")
library(psych)
install.packages("corrplot")
library(corrplot)

"""###Data reading from .csv format file"""

data <- read.csv("20 madhante.csv", sep = ";")
head(data)

"""##Descriptive Data Analysis

##Statistics from Numerical Data
"""

description <- describe(data)
description

num_duplicated_id <- sum(duplicated(data$Loan_ID))
cat("Number of Duplicated IDs:", num_duplicated_id, "\n")
factor_property_area <- as.factor(data$Property_Area)
num_unique_categories <- nlevels(factor_property_area)
cat("Number of Property Area Category:", num_unique_categories, "\n")
unique_categories <- unique(data$Property_Area)
cat("Semua Kategori Unik:",unique_categories)

"""##Statistics From Categorical Data"""

library(dplyr)
counts <- data %>%
  summarise(
    Male = sum(Gender == "Male"),
    Female = sum(Gender == "Female"),
    Working_at_Company = sum(Self_Employed == "No"),
    Self_Employed = sum(Self_Employed == "Yes"),
    Graduate = sum(Education == "Graduate"),
    Not_graduate = sum(Education == "Not graduate"),
    Semi_Urban = sum(Property_Area == "Semiurban"),
    Urban = sum(Property_Area == "Urban"),
    Rural = sum(Property_Area == "Rural")
  )
# Print the counts
print(counts)

"""##Inference
1. Loan Applicant incomes range from 0 (no income) to 72529.
2. Loan Co-Applicant incomes range from 0 ( no - Co-Applicant) to 24000.
3. Loan Amount range from 28 to 550.
4. Loan Amount term range from 6 to 480 months.
5. All IDs are unique and randomly alloted. They have no impact on the other data and can be dropped.
6. Most Applicant are male.
7. Most Applicant are working in a company.
8. All Applicant are a Graduate.

##Data Wrangling
Cleaning the data before visualizing it
"""

data <- data[, -which(names(data) == "Loan_ID")]
data

na_count_per_column <- colSums(is.na(data))

print("--------The NA values in each column------------")
print(na_count_per_column)

"""This code calculates the count of missing values (NA) in each column and prints the result. Identifying and handling missing data is crucial to ensure data quality before proceeding with further analysis."""

data <- na.omit(data)
na_count_per_column <- colSums(is.na(data))
print("--------The NA values in each column------------")
print(na_count_per_column)

data$Gender <- as.numeric(data$Gender == "male")
data$Education <- as.numeric(data$Education == "Graduate")
data$Married <- as.numeric(data$Married == "Yes")
data$Self_Employed <- as.numeric(data$Self_Employed == "Yes")

head(data)

numeric_columns <- data[sapply(data, is.numeric)]
correlation_matrix <- cor(numeric_columns)
corrplot(correlation_matrix, method = "color", type = "upper", diag = FALSE)

median_data <- data %>%
  group_by(Married) %>%
  summarise(median_income = median(ApplicantIncome, na.rm = TRUE))

mean_data <- data %>%
  group_by(Married) %>%
  summarise(mean_income = mean(ApplicantIncome, na.rm = TRUE))

print(median_data)
cat('\n')
print(mean_data)

median_data <- data %>%
  group_by(Married) %>%
  summarise(median_income = median(CoapplicantIncome, na.rm = TRUE))

print(median_data)

"""##Inference
 most cases of people with no co-applicants are not married.
"""

count_data <- data %>%
  group_by(Gender) %>%
  summarise(count = n())

print(count_data)